site_name: 菜鸟学架构
repo_url: https://github.com/Sharp-Enrich/LearnArchitecture
edit_uri: edit/master/docs/
site_description: 菜鸟学架构
site_author: Tacey Wong
copyright: ©2021 Tacey Wong
docs_dir: docs
nav:
  - 开始: index.md
  - 基础架构:
    - 01-架构到底是什么？: 01-架构到底是什么.md
    - 02-架构设计的历史背景: 02-架构设计的历史背景.md 
    - 03-架构设计的目的: 03-架构设计的目的.md
    - 04-复杂度来源：高性能: 04-复杂度来源-高性能.md
    - 05-复杂度来源：高可用: 05-复杂度来源-高可用.md
    - 06-复杂度来源：可扩展性: 06-复杂度来源-可扩展性.md
    - 07-复杂度来源：低成本、安全、规模: 07-复杂度来源-低成本-安全-规模.md
    - 08-架构设计三原则: 08-架构设计三原则.md
    - 09-架构设计原则案例: 09-架构设计原则案例.md
    - 10-架构设计流程：识别复杂度: 10-架构设计流程-识别复杂度.md
    - 11-架构设计流程：设计备选方案: 11-架构设计流程-设计备选方案.md
    - 12-架构设计流程：评估和选择备选方案: 12-架构设计流程-评估和选择备选方案.md
    - 13-架构设计流程：详细方案设计: 13-架构设计流程-详细方案设计.md
  - 高性能架构模式:
    - 14-高性能数据库集群：读写分离: 14-高性能数据库集群-读写分离.md
    - 15-高性能数据库集群：分库分表: 15-高性能数据库集群-分库分表.md
    - 16-高性能NoSQL: 16-高性能NoSQL.md
    - 17-高性能缓存架构: 17-高性能缓存架构.md
    - 18-单服务器高性能模式：PPC与TPC: 18-单服务器高性能模式-PPC与TPC.md
    - 19-单服务器高性能模式：Reactor与Proactor: 19-单服务器高性能模式-Reactor与Proactor.md
    - 20-高性能负载均衡：分类及架构: 20-高性能负载均衡-分类及架构.md
    - 21-高性能负载均衡：算法: 21-高性能负载均衡-算法.md


  - 高可用架构模式:
    - 22-想成为架构师，你必须知道CAP理论: 22-想成为架构师-你必须指导CAP理论.md
    - 23-想成为架构师，你必须掌握的CAP细节: 23-想成为架构师-你必须掌握的CAP细节.md
    - 24-FMEA方法，排除架构可用性隐患的利器: 24-FMEA方法-排除架构可用性隐患的利器.md
    - 25-高可用存储架构：双机架构: 25-高可用存储架构-双机架构.md
    - 26-高可用存储架构：集群和分区: 26-高可用存储架构-集群和分区.md
    - 27-如何设计计算高可用架构？: 27-如何设计计算高可用架构.md
    - 28-业务高可用的保障：异地多活架构: 28-业务高可用的保障-异地多活架构.md
    - 29-异地多活设计4大技巧: 29-异地多活设计4大技巧.md
    - 30-异地多活设计4步走: 30-异地多活设计4步走.md
    - 31-如何应对接口级的故障？: 31-如何应对接口级的故障.md  
  
  - 可扩展架构模式:
    - 32-可扩展架构的基本思想和模式: 32-可扩展架构的基本思想和模式.md
    - 33-传统的可扩展架构模式：分层架构和SOA: 33-传统的可扩展架构模式-分层架构和SOA.md
    - 34-深入理解微服务架构：银弹 or 焦油坑？: 34-深入理解微服务架构-银弹or焦油坑.md
    - 35-微服务架构最佳实践 - 方法篇: 35-微服务架构最佳实践-方法篇.md
    - 36-微服务架构最佳实践 - 基础设施篇: 36-微服务架构最佳实践-基础设施篇.md
    - 37-微内核架构详解: 37-微内核架构详解.md


  - 架构实战: 
    - 38-架构师应该如何判断技术演进的方向？: 38-架构师应该如何判断技术演进的方向.md
    - 39-互联网技术演进的模式: 39-互联网技术演进的模式.md
    - 40-互联网架构模板：“存储层”技术: 40-互联网架构模板-存储层技术.md
    - 41-互联网架构模板：“开发层”和“服务层”技术: 41-互联网架构模板-开发层和服务层技术.md
    - 42-互联网架构模板：“网络层”技术: 42-互联网架构模板-网络层技术.md
    - 43-互联网架构模板：“用户层”和“业务层”技术: 43-互联网架构模板-用户层和业务层技术.md
    - 44-互联网架构模板：“平台”技术: 44-互联网架构模板-平台技术.md
    - 45-架构重构内功心法第一式：有的放矢: 45-架构重构内功心法第一式-有的放矢.md
    - 46-架构重构内功心法第二式：合纵连横: 46-架构重构内功心法第二式-合纵连横.md
    - 47-架构重构内功心法第三式：运筹帷幄: 47-架构重构内功心法第三式-运筹帷幄.md
    - 48-再谈开源项目：如何选择、使用以及二次开发？: 48-再谈开源项目-如何选择-使用以及二次开发.md
    - 49-谈谈App架构的演进: 49-谈谈App架构的演进.md
    - 50-架构实战：架构设计文档模板: 50-架构实战-架构设计文档模板.md
 
  - 特别放送:
    - 架构专栏特别放送 | “华仔，放学别走！”第1期: 华仔-1.md
    - 架构专栏特别放送 | “华仔，放学别走！” 第2期: 华仔-2.md
    - 如何高效地学习开源项目 | “华仔，放学别走！” 第3期: 华仔-3.md
    - 架构师成长之路 | “华仔，放学别走！” 第4期: 华仔-4.md
    - 架构师必读书单 | “华仔，放学别走！” 第5期: 华仔-5.md
    - 加餐｜单服务器高性能模式性能对比: 单服务器高性能模式性能对比.md 
    - 加餐｜扒一扒中台皇帝的外衣: 扒一扒中台皇帝的外衣.md 

  - 结束:
    - 结束语-坚持，成就你的技术梦想: 结束语.md
    - 佛系程序员的月薪五万指南: 佛系程序员的月薪五万指南.md
    - 大牛养成指南（1）: 吃的草够多-你也能成为大牛.md
    - 大牛养成指南（2）: 先实现一个小目标吧-10000小时理论如何轻松落地.md
    - 大牛养成指南（3）: 天天写业务代码-如何成为技术大牛.md
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

extra:
  generator: false
# https://github.com/zhaoterryy/mkdocs-pdf-export-plugin
# pip install mkdocs-pdf-export-plugin
# plugins:
#     - pdf-export:
#         combined: true%           